# Generated by Django 4.1.2 on 2022-11-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_map', models.CharField(max_length=2500)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('x_start', models.IntegerField()),
                ('y_start', models.IntegerField()),
                ('num', models.IntegerField(unique=True)),
            ],
        ),
    ]
