# Generated by Django 4.1.2 on 2022-11-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='x_finish',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='level',
            name='y_finish',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='level',
            name='height',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='level',
            name='width',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='level',
            name='x_start',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='level',
            name='y_start',
            field=models.IntegerField(default=-1),
        ),
    ]
